"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.error = exports.success = exports.warning = exports.info = exports.notify = exports.ToastTypes = void 0;
const toast_1 = require("./toast");
Object.defineProperty(exports, "ToastTypes", { enumerable: true, get: function () { return toast_1.ToastTypes; } });
Object.defineProperty(exports, "notify", { enumerable: true, get: function () { return toast_1.notify; } });
Object.defineProperty(exports, "info", { enumerable: true, get: function () { return toast_1.info; } });
Object.defineProperty(exports, "warning", { enumerable: true, get: function () { return toast_1.warning; } });
Object.defineProperty(exports, "success", { enumerable: true, get: function () { return toast_1.success; } });
Object.defineProperty(exports, "error", { enumerable: true, get: function () { return toast_1.error; } });
